language: java
jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - mvn test jacoco:report coveralls:report
  - mvn javadoc:javadoc
  - mkdir target/site/apidocs/nl/han/ica/oopg/2.0 ;mv target/oopg-full.jar target/site/apidocs/nl/han/ica/oopg/2.0/oopg-full-2.0.jar

deploy:
    provider: pages
    local-dir: target/site/apidocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master