language: java
jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn javadoc:javadoc

deploy:
    provider: pages
    local-dir: oopg/target/site/apidocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master